Cysharp/MemoryPack

README.md
sandbox/Benchmark/Benchmarks/DeserializeTest.cs
sandbox/Benchmark/Benchmarks/SerializeTest.cs
sandbox/Benchmark/Benchmarks/Utf16VsUtf8.cs
sandbox/Benchmark/Micro/GetLocalVsStaticField.cs
sandbox/Benchmark/Micro/RawSerialize.cs
sandbox/Benchmark/Micro/Utf8Decoding.cs
sandbox/Benchmark/Program.cs
sandbox/SandboxConsoleApp/Program.cs
src/MemoryPack.Core/Formatters/ImmutableCollectionFormatters.cs
src/MemoryPack.Core/Formatters/InterfaceCollectionFormatters.cs
src/MemoryPack.Core/MemoryPackReader.cs
src/MemoryPack.Core/MemoryPackSerializationException.cs
src/MemoryPack.Core/MemoryPackSerializeOptions.cs
src/MemoryPack.Core/MemoryPackSerializer.NonGenerics.cs
src/MemoryPack.Core/MemoryPackSerializer.Serialize.cs
src/MemoryPack.Core/MemoryPackWriter.cs
src/MemoryPack.Streaming/MemoryPackStreamingSerializer.cs
tests/MemoryPack.Tests/StringTest.cs
tests/MemoryPack.Tests/WriterTest.cs

#13
new wire format String introduced.
using MemoryPackSerializeOptions.Utf8 to Serialize methods.
deserializer can detect which encoding used, we can deserialize both utf16 and utf8.

UTF8 String serialization

---

src/MemoryPack.Core/Internal/ReusableLinkedArrayBufferWriter.cs

Micro optimization based on following blog article: https://blog.marcgravell.com/2022/05/unusual-optimizations-ref-foreach-and.html
>Our use of ref var tmp with foreach here means that the L-value (tmp) is a managed pointer to the data - not the data itself; we have avoided copying the overweight value-type, and called the method in-place.
[SharpLab](https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYAYAEMEBYDcqG2CAdAEoCuAdsGALYCmpAkrYwE4D2ADgMqcAbmADGjAM6EURAMzY4mAMKoA3qkwaSANkxhamAGJcOAUQCGIgBYAKADJhxwADx8uTPsA6URwAHyZxN0Z7RwBKdU01FE0Y3X1gLmAzCEwAXkx0KVjNADNjRgtLTGtBMw5MYHoeOICgkOBw6OzMKObYhKSUgGp0yp5SVyYANWTKRizmgF8I7JgAdgrE5ImNaaaNGe044CUAWSNTQpGOOwdnQcYPLx9/QKZ6xpjW5r0djuS0jJXYvI4Cq2KpXKfRqii4EAgjB8YC41HEuzK4ksyVIAEFxHweGZqNY7sEzqFHs1nm0NO9ur0qgMgiMIGNvjE1m15otOt8mZpNjgdK89gdzFZyIwcsdTo4XEE …

Using ref var foreach for CollectionsMarshal.AsSpan

---

src/MemoryPack.Core/Formatters/MultiDimensionalArrayFormatters.cs
src/MemoryPack.Core/MemoryPackFormatterProvider.cs
tests/MemoryPack.Tests/ArrayFormatterTest.cs

It seems similar spelling fixed before  at `MessagePack for C#` repository: https://github.com/neuecc/MessagePack-CSharp/pull/472

Fix spelling of dimension.

---

.github/workflows/build-debug.yml
.github/workflows/build-release.yml

Enable Unity build on GitHub Actions.
Since 2021.2, `BuildOptions.EnableHeadlessMode` is obsoleted and won't work anymore, even set true.
Due to this Unity API change, UnitTest is currently disabled.
Following to obsolete message, it says [Use StandaloneBuildSubtarget.Server instead](https://github.com/Unity-Technologies/UnityCsReference/blob/6d3b44c3a737075fb8a31700450b2ee557a49d82/Editor/Mono/BuildPipeline.bindings.cs#L77) however it require dedicated server even we only need batch mode.
Currently searching alternative way, so let's disable Unit Test on Unity for a while.

feat: add Unity CI

---

src/MemoryPack.Core/Formatters/ArrayFormatters.cs
src/MemoryPack.Unity/Assets/Plugins/MemoryPack/Runtime/MemoryPack.Core/Formatters/ArrayFormatters.cs

Adds support for an IMemoryOwner<T> formatter.
I tried to match the syntax of the other formatters so I've based it off MemoryFormatter<T> and LazyFormatter<T>.
Let me know if this is correct.

Add IMemoryOwner<T> formatter

---

README.md
sandbox/SandboxConsoleApp/ForReadMe.cs
sandbox/SandboxConsoleApp/Program.cs
sandbox/SandboxWebApp/Program.cs
src/MemoryPack.Core/CustomFormatterAttributes.cs
src/MemoryPack.Core/Formatters/ArrayFormatters.cs
src/MemoryPack.Unity/Assets/Plugins/MemoryPack/Runtime/MemoryPack.Core/CustomFormatterAttributes.cs
src/MemoryPack.Unity/Assets/Plugins/MemoryPack/Runtime/MemoryPack.Core/Formatters/ArrayFormatters.cs
src/MemoryPack.Unity/UserSettings/Layouts/default-2021.dwlt
tests/MemoryPack.Tests/CustomFormatterTest.cs

Provides `ArrayPoolMemoryFormatterAttribute<T>`, `ArrayPoolReadOnlyMemoryFormatterAttribtue<T>`.
User annotate `Memory<T>` by `[ArrayPoolMemoryFormatter<T>]`.
When deserialized, inner data is used from `ArrayPool<T>.Shared.Rent`.
Return must be do by yourself.
For example, you can tie the pattern to Dispose and return manually.
```csharp
[MemoryPackable]
public partial class MyClass : IDisposable
{
[ArrayPoolMemoryFormatter<int>]
public Memory<int> LargeArray { get; }
public void Dispose()
{
// note: currently cannot determine if the data is from Pool or passed from outside, need to determine.
if (MemoryMarshal.TryGetArray<int>(LargeArray, out var segment))
{
ArrayPool<int>.Shared.Return(segment.Array!);
}
}
}
```

Deserialize array from ArrayPool

---

src/MemoryPack.Generator/MemoryPackGenerator.TypeScript.cs
src/MemoryPack.Generator/MemoryPackGenerator.cs
src/MemoryPack.Generator/TypeScriptMember.cs
tests/MemoryPack.Tests/GeneratorDiagnosticsTest.TypeScript.cs

I've modified the code to allow the nullable type propagation from C# to TypeScript. 
Also, I added a flag to keep the old behavior and enable this feature.
@neuecc give me your opinions about that and point me out if I'm forgetting something or if I've missed anything to read the configuration that I've created. 
I still don't know too much about the project structure and I'm learning about code generators too. Also, I'm not being able to compile it on my Mac because there is no support for Native AOT compilation apparently.
Closes #88

feat: use C# nullable markers to export ts nullable types

---

README.md

This is a recognized pattern that makes it really easy to discover how to consume the package.

Add nuget badge to README

---

src/MemoryPack.Generator/DiagnosticDescriptors.cs
src/MemoryPack.Generator/Extensions.cs
src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs
src/MemoryPack.Generator/MemoryPackGenerator.Parser.cs
tests/MemoryPack.Tests/ConstructorTest.cs

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case
Also list individual constructor parameters that cause MEMPACK006 so they are easier to track down.

support underscore naming convention (private/internal) fields

---

src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs

Quick and easy way of allowing end users to still have static constructors in their `[MemoryPackable]` structures

Potential Fix for Issue #167

---

.github/workflows/build-release.yml

* `create-release` workflow's `unitypackage-upload` and `unitypackage-path` inputs will be deprecated in future. This functionality can be replaced with `release-upload` and `release-asset-path`.

ci: switch create-release to use release-upload from unitypackage-upload

---

src/MemoryPack.Core/Formatters/InterfaceCollectionFormatters.cs
tests/MemoryPack.Tests/InterfaceFormatterTest.cs

#171 
( Similar to https://github.com/MessagePack-CSharp/MessagePack-CSharp/pull/1623

Fix deserialized behavior  ILookUp<>[] key is missing

---

sandbox/Benchmark/Benchmark.csproj
sandbox/ClassLibrary/ClassLibrary.csproj
sandbox/NativeAot/NativeAot.csproj
sandbox/SandboxConsoleApp/Program.cs
sandbox/SandboxConsoleApp/SandboxConsoleApp.csproj
src/MemoryPack.Core/MemoryPack.Core.csproj
src/MemoryPack.Core/MemoryPackSerializer.Deserialize.cs
src/MemoryPack.UnityShims/MemoryPack.UnityShims.csproj
tests/MemoryPack.Tests/MemoryPack.Tests.csproj

#189 
If there is only Deserialize<T>() in the source code, the AOT build seems to fail at runtime.
This could be avoided by adding DynamicallyAccessedMembers to the type parameter T of Deserialize<T>.
NOTE: 
The AOT build seems to work as far as I have tried.
However, if configure the project to `<IsAotCompatible>true</IsAotCompatible>` results in a lot of warnings. (IL2026 , IL3050) 
The parts of the project that use reflection seem to work, but it seems difficult to avoid warnings.
It seems possible to add `[RequiresUnreferencedCode]` or `[RequiresDynamicCode]` in addition to this PR.  But in the end, applications that uses MemoryPack should see warnings.

Fix AOT compatible of `Deserialize<T>`

---

sandbox/Benchmark/Benchmarks/ListFormatterVsDirect.cs
src/MemoryPack.Core/Formatters/CollectionFormatters.cs
src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs
src/MemoryPack.Unity/Assets/Plugins/MemoryPack/Runtime/MemoryPack.Core/Formatters/CollectionFormatters.cs
src/MemoryPack.Unity/Assets/RuntimeUnitTestToolkit/Editor/UnitTestBuilder.cs
src/MemoryPack.Unity/Assets/Scripts/MemoryPackObjects/MemberKinds.cs

#177, #202
NOTE:
- One of the warnings is due to a change in thef` Unsafe.AsRef` modifier . Removing the unnecessary `Unsafe.AsRef` seemed the simplest solution, so I did so..

Fix warnings for  source generator

---

src/MemoryPack.AspNetCoreMvcFormatter/MediaTypeHeaderValues.cs
src/MemoryPack.AspNetCoreMvcFormatter/MemoryPackInputFormatter.cs
src/MemoryPack.AspNetCoreMvcFormatter/MemoryPackOutputFormatter.cs

#229 
Since `application/x-memorypack` is a proprietary specification, it may be useful to reference constants.
Note: 
This changes has been tested in the SandboxWebApp project.

Expose media-type variable of `application/x-memorypack`

---

src/MemoryPack.Core/Compression/BrotliCompressor.cs

#243 
BrotoliEncoder.Compress seems to return `OperationState.DestinationTooSmall` even when the destination buffer is short.
If the length of one BufferSegment is very large (more than the bufferSize parameter), finalState was DestinationTooSmall, the method would complete.
( In #243, MemoryStream is used).

Fix BrotliCompressor.CopyToAsync buffer is not enough

---

src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs
src/MemoryPack.Generator/MemoryPackGenerator.Parser.cs
src/MemoryPack.Generator/MemoryPackGenerator.TypeScript.cs
tests/MemoryPack.Tests/Models/DefaultValues.cs

Fix #250, #252
In #242, to output the default value expression. 
However, it seems that name resolution may not work as it is.
For example,
```cs
public List<MyType> MyProperty = new List<MyType>();.
```
The default value of such an expression should have been as follows.
```cs
new global::System.Collections.Generic.List<MyNameSpace.MyType>();.
```

Fix problem when default value expression contains namespace

---

src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs
src/MemoryPack.Generator/Properties/launchSettings.json
tests/MemoryPack.Tests/Models/DefaultValues.cs

#255 #261
Fix compilation errors about default value analyzing for the following:
- Wrong literal when ctor argument is decimal
- Invaild `= null` emit when ctor argument is struct
- Fix to support for property default value of nested type .

Fix default value detection

---

src/MemoryPack.Core/Compression/BrotliCompressor.cs
tests/MemoryPack.Tests/BrotliTest.cs

Fix infinite loop in BrotliEncoder

---

README.md
src/MemoryPack.Core/Attributes.cs
src/MemoryPack.Generator/DiagnosticDescriptors.cs
src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs
src/MemoryPack.Generator/MemoryPackGenerator.Parser.cs
src/MemoryPack.Generator/ReferenceSymbols.cs
tests/MemoryPack.Tests/DefaultValueTest.cs
tests/MemoryPack.Tests/GeneratorDiagnosticsTest.cs
tests/MemoryPack.Tests/Models/DefaultValues.cs

#185 
Add `[SuppressDefaultInitialization]` attribute.
e.g)
```cs
[MemoryPackable]
partial class A
{
public int X;
public int Y = 12345;
[SkipOverwriteByDefault]
public float Z = 678.9f;
}
```
```cs
NEW:
value = new FieldDefaultValue()
{
@X = __X, 
@Y = __Y
};
if (3 <= count) value.@Z = __Z; // < Added this branch
```

Add attr to not overwrite Member with default value

---

src/MemoryPack.Core/MemoryPackSerializer.StateBackup.cs

Sometimes you want to invoke `MemoryPackSerializer.Serialize` while serializing another type (e.g. to serialize a complex nested structure into a byte array on serialization). And sometimes you want to do the same on deserialization. Since MemoryPack uses `[ThreadStatic]` to store its serializer/deserializer state, this doesn't work - unless you backup its state & reset it.
The provided implementation does exactly this. Currently we have to resort to CreateDelegate/ILEmit-based workaround to address that, this change would address the problem in more straightforward way.

feat: MemoryPackSerializer.ResetState, ResetReaderState, ResetWriterState

---

src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs

Adds `pragma warning disable CS0618` to generated *.MemoryPackFormatter.g.cs file

---

src/MemoryPack.Generator/DiagnosticDescriptors.cs
src/MemoryPack.Generator/MemoryPackGenerator.Parser.cs
tests/MemoryPack.Tests/GeneratorDiagnosticsTest.cs

I’ve resolved the [issue](https://github.com/Cysharp/MemoryPack/issues/300) where unmanaged structs were incorrectly allowed to use GenerateType.VersionTolerant with the following updates:
1. **Diagnostic MEMPACK041:** Triggers an error when an unmanaged struct is marked with VersionTolerant, as unmanaged structs should remain unchanged and cannot support version-tolerant serialization.
2. **Generator Fix:** The generator now correctly raises an error for unmanaged structs to ensure backward compatibility.
3. **Unit Test:** Added `MEMPACK041_UnmanagedStructCannotBeVersionTolerant` to validate the behavior.
Please review and provide feedback. Looking forward to improving MemoryPack’s reliability with this fix.

[issue-300] Fix for Unmanaged Structs Using GenerateType.VersionTolerant (MEMPACK041)

---

src/MemoryPack.Generator/DiagnosticDescriptors.cs
src/MemoryPack.Generator/MemoryPackGenerator.Emitter.cs
tests/MemoryPack.Tests/GeneratorDiagnosticsTest.cs
tests/MemoryPack.Tests/GeneratorTest.cs
tests/MemoryPack.Tests/Models/StandardType.cs

Nested class declarations now supported. Any amount of nesting should now work. Removed diagnostic MEMPACK002 as it no longer applies. added diagnostic MEMPACK042 to report that one of the containing types is not partial. Added unit tests for nested generation functionality and for new diagnostic.

Added support for nested classes

---

src/MemoryPack.Core/MemoryPackSerializer.Deserialize.cs
tests/MemoryPack.Tests/DeserializeTest.cs

Fix for generic struct deserialization when using ReadOnlySequence
